<?php

return array(
	'title'      => esc_html__( '404 Page Settings', 'bluebell' ),
	'id'         => '404_setting',
	'desc'       => '',
	'subsection' => true,
	'fields'     => array(
		array(
			'id'      => '404_source_type',
			'type'    => 'button_set',
			'title'   => esc_html__( '404 Source Type', 'bluebell' ),
			'options' => array(
				'd' => esc_html__( 'Default', 'bluebell' ),
				'e' => esc_html__( 'Elementor', 'bluebell' ),
			),
			'default' => 'd',
		),
		array(
			'id'       => '404_elementor_template',
			'type'     => 'select',
			'title'    => __( 'Template', 'bluebell' ),
			'data'     => 'posts',
			'args'     => [
				'post_type' => [ 'elementor_library' ],
			],
			'required' => [ '404_source_type', '=', 'e' ],
		),
		array(
			'id'       => '404_default_st',
			'type'     => 'section',
			'title'    => esc_html__( '404 Default', 'bluebell' ),
			'indent'   => true,
			'required' => [ '404_source_type', '=', 'd' ],
		),
		array(
			'id'      => '404_page_banner',
			'type'    => 'switch',
			'title'   => esc_html__( 'Show Banner', 'bluebell' ),
			'desc'    => esc_html__( 'Enable to show banner on blog', 'bluebell' ),
			'default' => true,
		),
		array(
			'id'       => '404_banner_title',
			'type'     => 'text',
			'title'    => esc_html__( 'Banner Section Title', 'bluebell' ),
			'desc'     => esc_html__( 'Enter the title to show in banner section', 'bluebell' ),
			'required' => array( '404_page_banner', '=', true ),
		),
		array(
			'id'       => '404_page_background',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Background Image', 'bluebell' ),
			'desc'     => esc_html__( 'Insert background image for banner', 'bluebell' ),
			'default'  => '',
			'required' => array( '404_page_banner', '=', true ),
		),
		array(
			'id'       => 'error_image',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( '404 Content BG Image', 'bluebell' ),
			'desc'     => esc_html__( 'Insert 404 Content BG image', 'bluebell' ),
			'default'  => '',
		),
		array(
			'id'    => '404_page_title',
			'type'  => 'text',
			'title' => esc_html__( '404 Page Heading', 'bluebell' ),
			'desc'  => esc_html__( 'Enter 404 section Page Heading that you want to show', 'bluebell' ),
		),
		array(
			'id'    => '404_bold_text',
			'type'  => 'textarea',
			'title' => esc_html__( '404 Tag Line Title', 'bluebell' ),
			'desc'  => esc_html__( 'Enter 404 page Tag Line Title that you want to show.', 'bluebell' ),
		),
		array(
			'id'    => '404_page_text',
			'type'  => 'textarea',
			'title' => esc_html__( '404 Page Description', 'bluebell' ),
			'desc'  => esc_html__( '', 'bluebell' ),
		),
		array(
			'id'    => 'back_home_btn',
			'type'  => 'switch',
			'title' => esc_html__( 'Show Button', 'bluebell' ),
			'desc'  => esc_html__( 'Enable to show back to home button.', 'bluebell' ),
			'default'  => true,
		),
		array(
			'id'       => 'back_home_btn_label',
			'type'     => 'text',
			'title'    => esc_html__( 'Button Label', 'bluebell' ),
			'desc'     => esc_html__( 'Enter back to home button label that you want to show.', 'bluebell' ),
			'default'  => esc_html__( 'Back To Home', 'bluebell' ),
			'required' => array( 'back_home_btn', '=', true ),
		),
		array(
			'id'     => '404_post_settings_end',
			'type'   => 'section',
			'indent' => false,
		),
	),
);