<?php
return array(
	'title'      => esc_html__( 'Logo Setting', 'bluebell' ),
	'id'         => 'logo_setting',
	'desc'       => '',
	'subsection' => false,
	'fields'     => array(
		array(
			'id'       => 'image_favicon',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Favicon', 'bluebell' ),
			'subtitle' => esc_html__( 'Insert site favicon image', 'bluebell' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/favicon.png' ),
		),
		array(
            'id' => 'normal_logo_show',
            'type' => 'switch',
            'title' => esc_html__('Enable Blue Color Logo', 'bluebell'),
            'default' => true,
        ),
		array(
			'id'       => 'dark_color_logo',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Blue Color Logo Image', 'bluebell' ),
			'subtitle' => esc_html__( 'Insert site Blue Color logo image', 'bluebell' ),
			'required' => array( 'normal_logo_show2', '=', true ),
		),
		array(
			'id'       => 'dark_color_logo_dimension',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Blue Color Logo Dimentions', 'bluebell' ),
			'subtitle' => esc_html__( 'Select Blue Color Logo Dimentions', 'bluebell' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show2', '=', true ),
		),
		array(
            'id' => 'normal_logo_show2',
            'type' => 'switch',
            'title' => esc_html__('Enable Red Color Logo', 'bluebell'),
            'default' => true,
        ),
		array(
			'id'       => 'light_color_logo',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Red Color Logo Image', 'bluebell' ),
			'subtitle' => esc_html__( 'Insert site Red Color logo image', 'bluebell' ),
			'required' => array( 'normal_logo_show2', '=', true ),
		),
		array(
			'id'       => 'light_color_logo_dimension',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Red Color Logo Dimentions', 'bluebell' ),
			'subtitle' => esc_html__( 'Select Red Color Logo Dimentions', 'bluebell' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show2', '=', true ),
		),
		array(
            'id' => 'mobile_logo_show',
            'type' => 'switch',
            'title' => esc_html__('Enable Mobile Logo', 'bluebell'),
            'default' => true,
        ),
		array(
			'id'       => 'mobile_logo',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Mobile Logo Image', 'bluebell' ),
			'subtitle' => esc_html__( 'Insert Mobile Logo Image', 'bluebell' ),
			'required' => array( 'mobile_logo_show', '=', true ),
		),
		array(
			'id'       => 'mobile_logo_dimension',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Mobile logo Dimentions', 'bluebell' ),
			'subtitle' => esc_html__( 'Select Mobile Logo Dimentions', 'bluebell' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'mobile_logo_show', '=', true ),
		),
		array(
			'id'       => 'logo_settings_section_end',
			'type'     => 'section',
			'indent'      => false,
		),
	),
);
